# config/mongoid.yml
development:
  clients:
    default:
      database: ror_app_dev
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5
  options:
    use_utc: false

test:
  clients:
    default:
      database: ror_app_test
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5
  options:
    use_utc: false

production:
  clients:
    default:
      database: ror_app_prod
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5
  options:
    use_utc: true
